### PR TITLE
Fix python parser issues

### LINKED ISSUE #1607: all kselftest results is not being parsed
```
/lava-8569803/0/tests/1_kselftest-tpm2
./kselftest.sh: 131: ./parse-output.py: not found
+ ../../utils/send-to-lava.sh ./output/result.txt
```
As result it is unable to report failures/regressions.

### PR DESCRIPTION
**Pull request by nuclearcat**
At current moment parser is being called from wrong directory and also doesn't handle case "not ok" that is "fail" properly.
This two commits fix this issue.
Tested manually at LAVA: https://lava.collabora.dev/scheduler/job/8570985
Fixes https://github.com/kernelci/kernelci-core/issues/1607

### CODE REVIEW

File: automated/linux/kselftest/kselftest.sh [hunk 1]
```diff
@@ -206,6 +206,7 @@ elif [ -n "${TST_CMDFILES}" ]; then
 else
     ./run_kselftest.sh 2>&1 | tee "${LOGFILE}"
 fi
+parse_output
 # shellcheck disable=SC2164
 cd - || exit
-parse_output
```
Comment (nkbelin) [inline automated/linux/kselftest/kselftest.sh:211]: I guess you can keep parse_output here but replace `cd -` by `cd saved_pwd` where saved_pwd is the current working directory before the script potentially uses the `cd` command at the beginning of the script.

Comment (nuclearcat) [reply automated/linux/kselftest/kselftest.sh:211]: Updated according suggestion, thanks!

Comment (nkbelin) [reply automated/linux/kselftest/kselftest.sh:211]: LGTM

**Comment by roxell** [comment]
I'm sorry, I realised that I merged this PR and the Linaro/test-definitions#421 PR. If you get an issue when you rebase, then you know why. =/

**Comment by gctucker** [comment]
Also worth mentioning, the 2nd commit in this PR is not on the `master` branch because there was this one already which had the same diff:
```
commit 551103991d4a52e9f962ac8dd0d66af74139dfcb (tag: kernelci-20230109.0)
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Tue Jan 3 09:06:27 2023 +0100

    automated: kselftest: parse-output: fix fail cases
    
    Forgot to set the fail output before removing the extra '_selftests_'
    from the output.
    
    Fixes: 65be76866f2d ("automated: kselftest: update parser")
    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
```
(just to confirm the fix is actually there)

**Comment by gctucker** [comment]
> I'm sorry, I realised that I merged this PR and the [Linaro#421](https://github.com/Linaro/test-definitions/pull/421) PR. If you get an issue when you rebase, then you know why. =/

@roxell Oh no, you've accidentally become a KernelCI co-maintainer! ;)  No worries, I did a manual rebase just to check and git says it's fine.
